version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Europe/Warsaw
      time: "10:00"
    labels: [deps, ci, workflow]

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      timezone: Europe/Warsaw
      time: "11:00"
    labels: [deps, python, pip]
